### ISSUE TITLE
Force close

### ISSUE THREAD

**Issue by IkhwanSI13** [IsaiasSantana/keyboard_utils#9]
with this error

`java.lang.RuntimeException: Unable to start activity ComponentInfo{com.test/com.test.MainActivity}: java.lang.UnsupportedOperationException: The new embedding does not support the old FlutterView.
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2449)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2509)
	at android.app.ActivityThread.access$1000(ActivityThread.java:153)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1373)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:5527)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629)
Caused by: java.lang.UnsupportedOperationException: The new embedding does not support the old FlutterView.
	at io.flutter.embedding.engine.plugins.shim.ShimRegistrar.view(ShimRegistrar.java:82)
	at br.com.keyboard_utils.KeyboardUtilsPlugin$Companion.registerWith(KeyboardUtilsPlugin.kt:16)
	at br.com.keyboard_utils.KeyboardUtilsPlugin.registerWith(KeyboardUtilsPlugin.kt)
	at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(GeneratedPluginRegistrant.java:20)
	at com.tes.MainActivity.configureFlutterEngine(MainActivity.kt:10)
	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onAttach(FlutterActivityAndFragmentDelegate.java:185)
	at io.flutter.embedding.android.FlutterActivity.onCreate(FlutterActivity.java:418)
	at android.app.Activity.performCreate(Activity.java:6303)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2402)
	... 9 more`

**Comment by IsaiasSantana** [comment]
@IkhwanSI13, check the new version 1.2.0. Does the problem still happen?

**Comment by IkhwanSI13** [comment]
> @IkhwanSI13, check the new version 1.2.0. Does the problem still happen?

wow, it's work now. thanks.
